- type: keycloak
  title: Keycloak IAM & SSO - Authentifizierung einfach und sicher gemacht
  name: Javaland Workshop
  date: '2022-03-17'
  location: Phantasialand, Brühl/Cologne
  url: https://www.javaland.eu
- type: keycloak
  title: Keycloak IAM & SSO - Authentifizierung einfach und sicher gemacht
  name: JAX Workshop
  date: '2022-05-12'
  location: Mainz / Online
  url: https://jax.de/performance-security/workshop-authentifizierung-einfach-und-sicher-gemacht-mit-keycloak-iam-und-sso/
- type: keycloak
  title: Keycloak IAM & SSO - Authentifizierung einfach und sicher gemacht
  name: IT Security Summit 2022
  date: '2022-05-17'
  location: Munich
  url: https://it-security-summit.de/it-security-summit/authentifizierung-einfach-und-sicher-gemacht-mit-keycloak-teil-1/
- type: keycloak
  title: Keycloak IAM & SSO - Authentifizierung einfach und sicher gemacht
  name: betterCode() Workshop
  date: '2022-05-18'
  location: Online
  url: https://api.bettercode.eu/veranstaltung-14096-se-0-authentifizierung-einfach-und-sicher-gemacht-mit-keycloak.html
